Q=1 What is OOP? List OOP concepts 
=>Object-oriented programming (OOP) 
is a computer programming model that
organizes software design around data,
or objects, rather than functions and logic.

=>Object. This is the basic unit of object oriented programming. ...

=>Class. When you define a class, you define a blueprint for an object. ...

=>Abstraction. ...
=>Encapsulation. ...
=>Inheritance. ...
=>Polymorphism. ...
=>Overloading.

Q=2 What is the difference between OOP and POP? 

=>OOP Defination:OOP stands for Object Oriented Programing.

=>POP stands for Procedural Oriented Programming.